import type { Metadata } from 'next'
import { PlatformLanding, faqSchema } from '@/components/landing/platform-landing'

const faqs = [
  { question: 'Does CommentMind replace Akismet?', answer: 'It can. CommentMind is designed to identify AI-generated and low-effort spam that pattern-based filters increasingly miss. Many users run it alongside Akismet during a transition period.' },
  { question: 'Will it reply to every comment automatically?', answer: 'No. You choose full-auto, review-before-publish, or moderation-only mode.' },
  { question: 'Does it slow down my WordPress site?', answer: 'No. Comment processing happens asynchronously through our servers, not on page load.' },
  { question: 'Can I control the tone of the AI replies?', answer: 'Yes. Tone and reply style are configurable per site.' },
]

export const metadata: Metadata = { title: { absolute: 'AI Comment Moderation for WordPress | CommentMind' }, description: 'Stop spam and auto-reply to blog comments on WordPress with AI. CommentMind understands your content and replies like you would — install in minutes.' }

export default function WordPressLanding() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema(faqs)) }} /><PlatformLanding eyebrow="WordPress integration" title="AI Comment Moderation & Auto-Reply for WordPress" description="Turn your WordPress comment section into a self-managing conversation. CommentMind reads every new comment, filters spam instantly, and replies to real questions using your own content as its knowledge base — no more digging through Akismet's spam folder or leaving readers waiting for an answer." features={[{ title: 'Works with any WordPress comment system', description: "Whether you're on native WordPress comments, Jetpack Comments, or a custom theme form, CommentMind plugs in without touching theme files." }, { title: 'Smarter than keyword-based spam filters', description: 'CommentMind reads intent and can distinguish a real reader question from well-written spam.' }, { title: 'Replies grounded in your content', description: 'Point CommentMind at posts, FAQs, or documentation for accurate answers in your voice.' }, { title: 'Lightweight, no performance hit', description: 'Moderation and reply generation happen off-site through our API, without bloated front-end libraries.' }]} steps={['Install the CommentMind plugin from the WordPress dashboard.', 'Connect your site and point it at the content you want it to learn from.', 'New comments are filtered and answered automatically, with a review queue when you need it.']} faqs={faqs} cta={{ label: 'Install CommentMind for WordPress — Free plan available', href: '/downloads/commentmind-ai-wordpress-plugin.zip' }} /></> }
